name: CI

on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  lint_with_ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install rye
        uses: eifinger/setup-rye@v4
      - name: Lint with ruff
        run: |
          rye lint -- --output-format=github
      - name: Format with ruff
        run: |
          rye fmt -- --diff
